server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://<host>:<port>/<DbName>
    username: example
    password: example
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show_sql: true
  main:
    web-application-type: servlet
